### ISSUE TITLE
HTTP Status code when HTTP Suspension triggered is always 500, not 509 as suggested in HTML content

### ISSUE THREAD

**Issue by troglodyne** [CpanelInc/mod_bwlimited#1]
Note on line 53:
      r->status = HTTP_INTERNAL_SERVER_ERROR;

Note on line 59:
		 "<HTML><HEAD>\n<TITLE>509 Bandwidth Limit Exceeded</TITLE>\n"

Why are we emitting a 500 when we are saying this is something else? Can this be fixed?

**Comment by HoustonDad** [comment]
Thanks, we've assigned this case EA-6666
